package com.example.MiniAutorizador.exception;

public enum ErrorCode {
    CARTAO_JA_EXISTENTE,
    CARTAO_INEXISTENTE,
    SENHA_INVALIDA,
    SALDO_INSUFICIENTE,
    SENHA_OBRIGATORIA,
    NUMERO_CARTAO_OBRIGATORIO,
    VALOR_INVALIDO
}